apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    certificate-authority: ${CA_CERT_BASE64}
users:
- name: kubelet
  user:
    client-certificate: ${WORKER_CERT_BASE64}
    client-key: ${WORKER_KEY_BASE64}
contexts:
- context:
    cluster: local
    user: kubelet
  name: kubelet-context
current-context: kubelet-context
